language: ruby
rvm:
    - 2.3.1
    
gemfile:
  - gemfiles/rails_5.gemfile
  - gemfiles/rails_4.gemfile
before_install: gem update rails --without production
install: gem install rails --without production