language: ruby
rvm:
    - 2.3.1
    - 2.2.5
    - 2.1
    - 2.0
gemfile:
  - gemfiles/rails_5.gemfile
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_3.gemfile
before_install: gem update rake
install: gem install rails